version: "3.9"

services:
  api:
    build: .
    container_name: backend_test_api
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app:rw
      - ./app.db:/app/app.db   # чтобы база сохранялась на диске и не терялась при перезапуске
    restart: unless-stopped
